database:
  filepath: "database/database.db"
  connect_timeout: 3

  token_length: 16
  token_charset: "abcdefghijklmmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"

  min_username_length: 3
  max_username_length: 32

connection:
  listen_address: "127.0.0.1"
  listen_port: 6666

  authentication_timeout: 5
  accept_backlog: 3